USE CHURCH_MANAGEMENT;

SELECT * FROM MEMBERS;
SELECT * FROM USERS;
SELECT * FROM ROLE;
SELECT * FROM FUNCTIONS;
SELECT * FROM MINISTRYS;
SELECT * FROM EVENTS;
SELECT * FROM MENUS ORDER BY POSITION ASC;

