USE CHURCH_MANAGEMENT;

DROP TABLE IF EXISTS EVENTS;
DROP TABLE IF EXISTS MEMBERS;
DROP TABLE IF EXISTS MINISTRYS;
DROP TABLE IF EXISTS MENUS;
DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS ROLE;
DROP TABLE IF EXISTS FUNCTIONS;


CREATE TABLE IF NOT EXISTS ROLE(
	ID INT AUTO_INCREMENT PRIMARY KEY,
	NAME VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS FUNCTIONS(
  ID INT AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(50) NOT NULL,
  DESCRIPTION VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS USERS (
	ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    USERNAME VARCHAR(50)  UNIQUE NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    PASSWORD VARCHAR(100) NOT NULL,
    IMAGE VARCHAR (500),
    ROLE_ID INT NOT NULL
);

CREATE TABLE IF NOT EXISTS MENUS(
	POSITION INT NOT NULL,
	NAME VARCHAR(100) NOT NULL UNIQUE,
    PATH VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE MINISTRYS (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(50) NOT NULL,
  DESCRIPTION VARCHAR(100)
);

CREATE TABLE MEMBERS (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(100) NOT NULL,
  BIRTH_DATE DATETIME NOT NULL,
  ADDRESS VARCHAR(200),
  EMAIL VARCHAR(100),
  PHONE VARCHAR(20) NOT NULL,
  MINISTRY_ID INT,
  ROLE_ID INT NOT NULL,
  FUNCTION_ID INT NOT NULL,
  FOREIGN KEY (ROLE_ID) REFERENCES ROLE(ID),
  FOREIGN KEY (MINISTRY_ID) REFERENCES MINISTRYS(ID),
  FOREIGN KEY (FUNCTION_ID) REFERENCES FUNCTIONS(ID)
);

CREATE TABLE EVENTS (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(100) NOT NULL,
  DATE DATETIME NOT NULL,
  LOCAL VARCHAR(200) NOT NULL,
  DESCRIPTION VARCHAR(200),
  MEMBER_ID INT NOT NULL,
  FOREIGN KEY (MEMBER_ID) REFERENCES MEMBERS(ID)
);
