SELECT M.NAME AS MEMBER, E.NAME AS EVENT FROM MEMBERS M
INNER JOIN EVENTS E ON E.MEMBER_ID = M.ID;

SELECT MN.NAME, COUNT(M.ID) AS QTD FROM MINISTRYS MN
INNER JOIN MEMBERS M ON M.MINISTRY_ID = MN.ID 
GROUP BY MN.NAME;

SELECT M.NAME, TIMESTAMPDIFF(YEAR, M.BIRTH_DATE, CURDATE()) AS AGE, M.ADDRESS, M.EMAIL, M.PHONE, MN.NAME AS MINISTRY
FROM MEMBERS M
INNER JOIN MINISTRYS MN ON MN.ID = M.MINISTRY_ID
WHERE TIMESTAMPDIFF(YEAR, M.BIRTH_DATE, CURDATE()) > 18
